name: üèÅ Build Portable MLIR Toolchain

on:
  workflow_dispatch:
  # pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  REF: llvmorg-21.1.5

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2022, windows-11-arm]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v5.0.0
      - run: choco install -y zstandard
      - name: Restore ccache
        uses: actions/cache@v4.3.0
        with:
          path: ~/.ccache
          key: ccache-windows-${{ env.REF }}-${{ github.ref_name }}
          restore-keys: |
            ccache-windows-${{ env.REF }}-
            ccache-windows-
      - name: Build
        run: bash scripts/toolchain/windows/build.sh -r "$REF" -a "${{ matrix.runs-on == 'windows-2022' && 'AMD64' || 'ARM64' }}"
      - name: Upload archive
        uses: actions/upload-artifact@v5.0.0
        with:
          name: ${{ matrix.runs-on }}-archive
          path: llvm-mlir_*.tar.zst
          if-no-files-found: error
