name: üèÅ Build Portable MLIR Toolchain

on:
  workflow_call:
    inputs:
      ref:
        description: "llvm-project ref or tag (e.g., llvmorg-21.1.0)"
        required: true
        type: string

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  REF: ${{ inputs.ref }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2022, windows-11-arm]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v5.0.0
      - run: choco install -y zstandard
      - name: Restore ccache
        uses: actions/cache@v4.3.0
        with:
          path: ~/.ccache
          key: ccache-windows-${{ env.REF }}-${{ github.ref_name }}
          restore-keys: |
            ccache-windows-${{ env.REF }}-
            ccache-windows-
      - name: Build
        run: |
          choco install -y zstandard
          & ${{ github.workspace }}\scripts\toolchain\windows\build.ps1 -ref ${{ env.REF }} -install_prefix ${{ github.workspace }}\llvm-install
      - name: Upload archive
        uses: actions/upload-artifact@v5.0.0
        with:
          name: ${{ matrix.runs-on }}-archive
          path: llvm-mlir_*.tar.zst
          if-no-files-found: error
